trigger:
- task: NodeTaskRunnerInstaller@0
  inputs:
    nodeVersion: '6'
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '1805b92d-4c00-48f9-becf-9b43175fcb91'
    appType: 'webAppLinux'
    appName: 'mywebsite'
    package: '$(Build.ArtifactStagingDirectory)'